### ISSUE TITLE
Disable Die By Starvation when Fasting

### ISSUE THREAD

**Issue by alwanfauzan** [TheTechdoodle/disable-eat#1]
**Feature Request**

Disable Die Of Hunger when fasting, when its fasting time and saturation bar is empty, don't let players die from starvation/hunger. But this behavior only activated when fasting, vice versa.

Make this as an options/toggle in config file.

Thanks !

**Comment by techchrism** [comment]
Added with f1aa0dfb82942c620faf93ca248f4d1801eb4ad3
